baseURL = "https://1-eq4.pages.dev/"
languageCode = "en-us"
title = "My Midnight Blog"
theme = "midnight"  # Must match the folder name inside themes/ or root if local

paginate = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  dateFormat = "2006-01-02"

  homeInfoParams = { 
    Title = "Welcome to my Midnight Terminal blog!",
    Content = "This is the homepage. Posts will appear below."
  }

[languages]
  [languages.en]
    languageName = "English"
    title = "My Midnight Blog"

    [languages.en.params]
      subtitle = "A retro terminal-style blog"
      owner = "The"
      copyright = "Â© 2026"

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 10